/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Drawer: typeof import('primevue/drawer')['default']
    GenericCard: typeof import('./src/shared/components/GenericCard.vue')['default']
    GenericDataToolbar: typeof import('./src/shared/components/GenericDataToolbar.vue')['default']
    GenericEmptyState: typeof import('./src/shared/components/GenericEmptyState.vue')['default']
    GenericExcelExport: typeof import('./src/shared/components/GenericExcelExport.vue')['default']
    GenericExport: typeof import('./src/shared/components/GenericExport.vue')['default']
    GenericInfo: typeof import('./src/components/GenericInfo.vue')['default']
    GenericOrganizationCart: typeof import('./src/shared/components/icons/GenericOrganizationCart.vue')['default']
    GenericTable: typeof import('./src/shared/components/GenericTable.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MainSidebar: typeof import('./src/components/MainSidebar.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    MenuItem: typeof import('./src/shared/components/forMainLayout/MenuItem.vue')['default']
    Message: typeof import('primevue/message')['default']
    NavButton: typeof import('./src/components/NavButton.vue')['default']
    OrganizationChart: typeof import('primevue/organizationchart')['default']
    Paginator: typeof import('primevue/paginator')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveButton: typeof import('./src/components/SaveButton.vue')['default']
    Select: typeof import('primevue/select')['default']
    SidebarContent: typeof import('./src/shared/components/forMainLayout/SidebarContent.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    StatCard: typeof import('./src/shared/components/StatCard.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Toast: typeof import('primevue/toast')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
